package br.com.suacifra.utils

object Config {
    const val SUA_CIFRA_DATABASE = "suaCifraDatabase.db"
    const val SUA_CIFRA_DATABASE_VERSION = 2

    const val SHARED_PREFERENCE_FILE_KEY = "br.com.suacifra.PREFERENCE_FILE_KEY"
    const val SHARED_PREFERENCE_SIGN_IN_BOOLEAN_KEY = "br.com.suacifra.PREFERENCE_SIGN_IN_BOOLEAN_KEY"

    const val SHARED_PREFERENCE_EDIT_SEQUENCE_MODE_BOOLEAN_KEY = "br.com.suacifra.PREFERENCE_EDIT_SEQUENCE_MODE_BOOLEAN_KEY"
    const val SHARED_PREFERENCE_EDIT_SEQUENCE_MODE_SEQUENCE_STRING_KEY = "br.com.suacifra.PREFERENCE_EDIT_SEQUENCE_MODE_SEQUENCE_STRING_KEY"
    const val SHARED_PREFERENCE_EDIT_CIFRA_MODE_BOOLEAN_KEY = "br.com.suacifra.PREFERENCE_EDIT_CIFRA_MODE_BOOLEAN_KEY"
    const val SHARED_PREFERENCE_EDIT_CIFRA_MODE_NAME_STRING_KEY = "br.com.suacifra.PREFERENCE_EDIT_CIFRA_MODE_NAME_STRING_KEY"
    const val SHARED_PREFERENCE_EDIT_CIFRA_MODE_SINGER_NAME_STRING_KEY = "br.com.suacifra.PREFERENCE_EDIT_CIFRA_MODE_SINGER_NAME_STRING_KEY"
    const val SHARED_PREFERENCE_EDIT_CIFRA_MODE_TONE_STRING_KEY = "br.com.suacifra.PREFERENCE_EDIT_CIFRA_MODE_TONE_STRING_KEY"
    const val SHARED_PREFERENCE_EDIT_CIFRA_MODE_SEQUENCE_SET_STRING_KEY = "br.com.suacifra.PREFERENCE_EDIT_CIFRA_MODE_SEQUENCE_SET_STRING_KEY"
    const val SHARED_PREFERENCE_EDIT_NOTES_MODE_BOOLEAN_KEY = "br.com.suacifra.PREFERENCE_EDIT_NOTES_MODE_BOOLEAN_KEY"
    const val SHARED_PREFERENCE_EDIT_NOTES_MODE_TITLE_STRING_KEY = "br.com.suacifra.PREFERENCE_EDIT_NOTES_MODE_TITLE_STRING_KEY"
    const val SHARED_PREFERENCE_EDIT_NOTES_MODE_BODY_STRING_KEY = "br.com.suacifra.PREFERENCE_EDIT_NOTES_MODE_BODY_STRING_KEY"
    const val SHARED_PREFERENCE_EDIT_SEQUENCE_MODE_SEQUENCE_INDEX_KEY = "br.com.suacifra.PREFERENCE_EDIT_SEQUENCE_MODE_SEQUENCE_INDEX_KEY"
    const val SHARED_PREFERENCE_ADD_CIFRA_MODE_NAME_EDIT_TEXT_KEY = "br.com.suacifra.PREFERENCE_ADD_CIFRA_MODE_NAME_EDIT_TEXT_KEY"
    const val SHARED_PREFERENCE_ADD_CIFRA_MODE_SINGER_NAME_EDIT_TEXT_KEY = "br.com.suacifra.PREFERENCE_ADD_CIFRA_MODE_SINGER_NAME_EDIT_TEXT_KEY"
    const val SHARED_PREFERENCE_EDIT_NOTES_MODE_ID_INT_KEY = "br.com.suacifra.PREFERENCE_EDIT_NOTES_MODE_ID_INT_KEY"
    const val SHARED_PREFERENCE_EDIT_CIFRA_MODE_ID_INT_KEY = "br.com.suacifra.PREFERENCE_EDIT_CIFRA_MODE_ID_INT_KEY"
}