package br.com.suacifra.utils

object Config {
    const val SHARED_PREFERENCE_FILE_KEY = "br.com.suacifra.PREFERENCE_FILE_KEY"
    const val SHARED_PREFERENCE_SIGN_IN_BOOLEAN_KEY = "br.com.suacifra.PREFERENCE_SIGN_IN_BOOLEAN_KEY"

    const val SUA_CIFRA_DATABASE = "suaCifraDatabase.db"
    const val SUA_CIFRA_DATABASE_VERSION = 2

    const val NOTE_ID_BUNDLE_KEY = "NOTE_ID_KEY"
    const val NOTE_TITLE_BUNDLE_KEY = "NOTE_TITLE_KEY"
    const val NOTE_BODY_BUNDLE_KEY = "NOTE_BODY_KEY"

    const val CIFRA_ID_BUNDLE_KEY = "CIFRA_ID_KEY"
    const val CIFRA_NAME_BUNDLE_KEY = "CIFRA_NAME_KEY"
    const val CIFRA_TONE_BUNDLE_KEY = "CIFRA_TONE_KEY"
    const val CIFRA_SINGER_NAME_BUNDLE_KEY = "CIFRA_SINGER_NAME_KEY"
    const val CIFRA_SEQUENCE_STRING_BUNDLE_KEY = "CIFRA_SEQUENCE_STRING_KEY"
    const val CIFRA_ONE_SEQUENCE_BUNDLE_KEY = "CIFRA_ONE_SEQUENCE_KEY"
    const val CIFRA_ONE_SEQUENCE_DELETE_BOOLEAN_BUNDLE_KEY = "CIFRA_ONE_SEQUENCE_DELETE_BOOLEAN_KEY"
    const val CIFRA_ONE_SEQUENCE_INDEX_BUNDLE_KEY = "CIFRA_ONE_SEQUENCE_INDEX_KEY"
    const val CIFRA_ONE_SEQUENCE_ADD_BOOLEAN_BUNDLE_KEY = "CIFRA_ONE_SEQUENCE_ADD_BOOLEAN_KEY"
    const val CIFRA_ONE_SEQUENCE_EDIT_BOOLEAN_BUNDLE_KEY = "CIFRA_ONE_SEQUENCE_EDIT_BOOLEAN_KEY"
}